# Generated by Django 2.2.7 on 2019-11-12 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=400)),
                ('thumbnail_url', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('inventory', models.IntegerField()),
                ('margin', models.DecimalField(decimal_places=2, max_digits=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('stars', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, max_length=40)),
                ('last_name', models.TextField(blank=True, max_length=40)),
                ('company', models.TextField(blank=True, max_length=100)),
                ('address_line_one', models.TextField(blank=True, max_length=100)),
                ('address_line_two', models.TextField(blank=True, max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
