# Generated by Django 2.2.7 on 2019-11-14 14:13

from django.db import migrations
from django.contrib.auth.models import User



def load_fixture(apps, schema_editor):
    User.objects.create_user(username='guest', email='guest@123.com', password='password')

    
def unload_fixture(apps, schema_editor):
    "Brutally deleting all entries for this model..."

    MyModel = apps.get_model("fashion", "User")
    MyModel.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0002_initial_products'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
